# --- !Ups

UPDATE GAME SET played = false;
ALTER TABLE GAME ALTER COLUMN played TYPE boolean;
ALTER TABLE GAME ALTER COLUMN played SET NOT NULL;

# --- !Downs

ALTER TABLE GAME ALTER COLUMN played DROP NOT NULL;
ALTER TABLE GAME ALTER COLUMN played TYPE Boolean;